name: Node.js CI

on:
  push:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14.x'

    - name: Install dependencies
      run: npm install

    - name: Run lint
      run: npm run lint

    - name: Build Docker image
      run: docker build -t devops-github-actions .

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Tag Docker image
      run: docker tag devops-github-actions:latest katekn/devops-github-actions:latest

    - name: Push Docker image
      run: docker push katekn/devops-github-actions:latest

    - name: Test Docker image
      run: |
        docker pull devops-github-actions:latest
        docker run -d --name my-container -p 80:80 devops-github-actions:latest
        sleep 5
        curl -I localhost:8080
        docker stop my-container
        docker rm my-container
